### PR TITLE
add type for Apple Silicon builds

### PR DESCRIPTION
**Pull request by richardlau**
Fixes: https://github.com/nodejs/nodejs-dist-indexer/issues/14

### CODE REVIEW

**Comment by richardlau** [comment]
cc @nodejs/build

**Review by Trott — APPROVED** [review]

**Review by evanlucas — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Comment by ljharb** [comment]
(ignore that green check, mine should be grey)

**Comment by richardlau** [comment]
I have access to update the server this runs on but I don't think I have permission to update this module in the npm registry.
cc @rvagg @jbergstroem (those listed by `npm owner ls nodejs-dist-indexer`).

**Review by rvagg — APPROVED** [review]
added you to npm @richardlau

**Comment by richardlau** [comment]
Thanks @rvagg! I've published v1.5.0, successfully published to npm and updated the server.

**Pull request merged**
