### PR TITLE
infra: new test

### PR DESCRIPTION
**Pull request by AugustinMauroy**
#34

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
cc @rvagg

**Comment by rvagg** [comment]
I'm not really up on the new node test runner, is this directory structure essential to make that work? Is `src` and `src/__test__` a mandatory thing for that?

**Comment by AugustinMauroy** [comment]
> I'm not really up on the new node test runner, is this directory structure essential to make that work? Is src and src/__test__ a mandatory thing for that?

absolutely not, but having a directory that differentiates between source code and tests seems important to me.

**Comment by rvagg** [comment]
ok, but `__test__` isn't really idiomatic, and putting it inside `src` even less so

how about just `test` and `src`?

it is nice to see the tests move out of the files though

**Comment by AugustinMauroy** [comment]
Updated

**Review by richardlau — APPROVED** [review]

**Comment by rvagg** [comment]
sorry to be picky @AugustinMauroy, would you mind switching to `test` instead of `tests`? it's a bit more typical and even the new tests [API docs](https://nodejs.org/api/test.html#running-tests-from-the-command-line) say it uses it when looking for tests (I know your filenames do this).

**Review by rvagg — APPROVED** [review]
👌 (holding my nose at the package-lock, it's not unreasonable for this package I suppose)

**Pull request merged**
