### PR TITLE
feat: add x64-debug

### PR DESCRIPTION
**Pull request by matthewkeil**
**NOTE: Reopened PR #25.  Please see that PR for comments and commit history**

This adds support for an unofficial-build that is added in [nodejs/unofficial-builds#107](https://github.com/nodejs/unofficial-builds/pull/112)

attn: @rvagg

### CODE REVIEW

**Comment by matthewkeil** [comment]
Please double check this.  I think its correct but would love a keen eye @rvagg !!!  Thanks again!

**Comment by matthewkeil** [comment]
Thanks @richardlau!

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Comment by matthewkeil** [comment]
Thanks @UlisesGascon !

**Review by rvagg — APPROVED** [review]

**Pull request merged**
